travis:
  secure:
    BINSTAR_TOKEN: qq5H1v3RZ94VNaJulSunSJMCMMk7vBdOh+ImppGZRmMM0ZiRPtocWvyg8PXzUa2Z1dRFTIpcfhPoAGaMFq05F9wUp9+LjoJ9wYlZlPZ5w+d6MzGv4SJ8Wp2R3JliiRjadr+Wn/B/dOPMeSYMqHvWuORCIAFSTMoONsZmHNcgoAp4KU8sXJqDlq8wv29b31qY72OIHHD2Z5xdqCrHU83JtHi6CFISdAZQmJbdFMvfGvnKWNTQXSqz1jNLL5l+rTcz2dm9LBYUDb9Aok68v246CDb3hqHGfmMVbU+RxyZe9RHMK1aMMzHgjrcXwpbRPeI8bjHl84YKAg4RYVOBHhgbm8LAWYk5wkiXRE/NdCdgx3nBc6oXbzhhFQLY/UWvGrqa+JzAqej/jq1nWcvg75OII7LwxIkIqjl0w0DFCeOdU3/TY+eNvTZ/pXbsk0A0ka4qz7ICQpjsh3rdHnJylY2buQCVY0sqdS4q6pAgw4BlwhyOc+qnCXTVrqh3FkwIRGNYPxWwFto4fDG/RYH2oh/qjjilIg2BXpRCM3vn8n9QIGGPWf0LXvZd51tsW76iTXZ6S2UjbRnGptMc+sWFqqQuZ0TTFneIs0rePF0KAknpCDcecI4+tFbwvxquohpGmudP/zA0eHK1/n0mynRCD4Dv6fs7aQjSLCp5tMFeNKBEk0s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
